name: pygraf
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - basemap
  - basemap-data-hires=1.2.1
  - pynio=1.5.5
  - matplotlib
  - metpy=0.12.1
  - pylint
  - pytest
  - pyyaml=5.3.1
  - xarray=0.15.1
