name: pygraf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.10
  - basemap=1.2.0
  - basemap-data-hires=1.2.1
  - pynio=1.5.5
  - matplotlib=3.2.0
  - metpy=0.12.1
  - pylint=2.4.0
  - pytest=6.1.0
  - pyyaml=5.3.1
  - xarray=0.15.1
